version: "3"

services:
  db:
    image: postgres:15
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    container_name: ${PROJECT_NAME}-db
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./db/database:/var/lib/postgresql/data
    restart: always

  apiserv:
    build:
      context: .
      dockerfile: ./deployments/Dockerfile
    container_name: ${PROJECT_NAME}
    ports:
      - ${SERVER_PORT}:${APP_PORT}
    volumes:
      - ./logs:/app/logs
    restart: always
    depends_on:
      - db

